---
title: "Assignment1"
author: "Kelsie Ferin"
date: "January 29, 2018"
output: html_document
---


## Assignment 1 

This is the main file for Assignment 1. I copied this from Andy.

```{r}
h=6.62606896e-34
c=2.99792458e8
k=1.3806504e-23 
lambda = seq(1e-8,1e-4, by=1e-8)
T = 6000


y=(2*pi*h*(c^2))/(lambda^5)*(1./(exp((h*c)/(lambda*k*T))-1))


T2 = 288
y2=(2*pi*h*(c^2))/(lambda^5)*(1./(exp((h*c)/(lambda*k*T2))-1))
plot(1e6*lambda,1e-6*1e-6*y, xlim=c(0.0,5.0),ylim=c(0.0,100.0), xlab='Wavelength (um)', ylab='spectral emittance (MW/m2/um)')
# par(new=T)
# plot(1e6*lambda,1e-6*1e-6*y2, xlim=c(0.0,10.0), ylim=c(0.0,1/10000.0), xlab='', ylab='', axes=F)
# par(new=F)
plot(1e6*lambda,1e-6*1e-6*y2, xlim=c(0.0,50.0), ylim=c(0.0,3*1e-5), xlab='Wavelength (um)', ylab='spectral emittance (MW/m2/um)')
```

``

Kelsie and Theo chuck for Assign 1:
Pg 105 on physics book PDF

```{r}
lambda2 = seq(4.00e-7,7.05e-7, by=1e-10)
bookT = 5800
y = (h*c)/(lambda2*k*bookT)
plot(lambda2,y,xlab='Wavelength (m)',ylab='Plancks Exponential')

```

```{r}
I=((2*pi)*(h)*(c**2)/((lambda2**5)*(exp(y)-1)))
plot(lambda2,I,xlab='Wavelength (m)',ylab='Spectral Emittance (W/m^2/m)')
```
```{r}
Ilambda = (I*(max(lambda2)-min(lambda2)))*1e-6
plot(I,Ilambda,xlab='Spectral Emittance (W/m^2/m)',ylab='Intensity (MW/m^2)')

```
look at spectrum from class and compare actual amount of energy in waveband to this data
compare it
annotate the code explain units for parameters
dynamic to look at different wavebands 

